language: cpp
compiler:
  - gcc
  - clang
before_script:
 - wget -q https://github.com/monsdar/CxxProf-Thirdparty-gcc64/archive/master.zip 
 - unzip -o -q master.zip
 - mv CxxProf-Thirdparty-gcc64-master/thirdparty .
 - chmod +x ./script/build.py
 - chmod +x ./script/test.py
 - export LD_LIBRARY_PATH=$(pwd)/thirdparty/pluma/lib/
script: ./script/build.py --native-cmake
after_script:
 - cat ./build/cxxprof_static/build_cxxprof_tutorial_release_out.log
 - ./script/test.py --native-ctest